In [1]:
import pandas as pd
from src.config import PLAYERS_NAME_FILE, HARD_ITERATION_LIMIT, MATCHS_FILE, MATCHS_EXPIRATION_LIMIT, MATCHS_ENHANCED_FILE

In [2]:
df = pd.read_csv(PLAYERS_NAME_FILE)
df.head()

            name                                 puuid
0   White Chroma  1d42a11a-8e1c-582d-abe5-89a7ae5781b4
1    Noz Chronyx  80ae6d0d-1794-51d2-83f2-be4c4bab9589
2            R3D  14dc51c0-3356-56e1-9631-80b4867f6373
3     Marekhanzl  92895938-b267-5d1b-9381-0f4d7679d9c3
4  fritierteEnte  7bdb56d2-cdf8-5a23-bda3-c3c27a05af31

In [3]:
df.sample(100, replace=True)['name'].to_list()

['IchBinKrasus',
 'sushines',
 'KOI pika',
 'vivi',
 'andresinho',
 'Pirulo Jungly',
 'miguuel',
 'Enemy',
 'SinaI',
 'Poxy27',
 'camillou',
 'GG 月亮怜悯',
 'Patrickus Star',
 'Sooftes',
 'benimitica19',
 '东汉末年闹鸡瘟丁真怒斩蔡徐坤',
 'CACAFONDANTMIAM',
 'Selecta',
 'rotpot',
 'aku',
 'BİZİ BİTİRDİN BE',
 '04ko',
 'i miss herr',
 'DontBWeird',
 'lalex',
 'TRIXX',
 'Cris',
 'kampfkeks',
 '7 lies',
 'Turab',
 'Patrick',
 'grafface',
 'RedAventurine',
 'ZeDoody',
 'Snjerku',
 'ALONE B 0 Y',
 'RISTLIKE',
 'AnthonyEdwards',
 'TES',
 'LaveToiLeCu',
 'x6yz',
 'Bartolinka',
 'OsuRRtanBoğA',
 'Matzord',
 'Agustus3',
 'SussyUwe',
 'STRAUS',
 'NayoBd',
 'POTATO300potato',
 'IMM0RTAL',
 'Dxd SpeedyMeto',
 'GoEasyImCrap',
 'Dumm',
 'Petetillo',
 'Nxc0',
 'onigiri14',
 'ATM',
 'pooping mys',
 'GrustnoiTochka',
 'MissCookie',
 'Germs Red',
 'gitr0rr',
 'surime',
 'rsRyker',
 'AHMAD',
 '1hunderfi5h',
 'Felgarâth',
 'Jack2Cactus10',
 'TMP Tetsu',
 'fosepull',
 'Luna',
 'ツLUCASツ',
 'Kaelie',
 'Abdulrahman382',
 'Zanox99',
 'erti brokeboi',
 'Maffy',
 'Tatolekmg',
 'ANDROXUS',
 '122gdhfu',
 'Pud King',
 'Raixsowwito',
 'Aertepyqua',
 'ManuelClark',
 'Bluffled',
 'Krevett',
 'PivasNN',
 'WachoSSJ',
 'gernorb',
 'n3llylotti',
 'The Peak',
 'ANGELHC31',
 'SHADOW DEXTER',
 'M D',
 'AlsoNotHim',
 'EstellAv',
 'ウルトラMT',
 'KYOツ',
 'qqmoi',
 'Arnesin']

In [4]:
matchs_dataframe = pd.read_csv(MATCHS_FILE, parse_dates=['start_datetime'])
matchs_dataframe.head()

,match_id,start_datetime,winner_team,blue_0_name,blue_0_puuid,blue_1_name,blue_1_puuid,blue_2_name,blue_2_puuid,blue_3_name,...,red_0_name,red_0_puuid,red_1_name,red_1_puuid,red_2_name,red_2_puuid,red_3_name,red_3_puuid,red_4_name,red_4_puuid
0,370472f6-8db6-4f66-832e-2baae9111568,2025-06-30 18:47:00,blue,LEVIA10,e8ef8695-423f-57c3-b5d7-7d013f79ec02,Aiz3n2107,4e680746-7a6d-55ba-8410-a918ea9d16eb,BurritoBandit,91c54dbe-0e4d-5918-bfc5-725f9012db9b,afraid of fems,...,Zandal,ae6fdb13-7f1e-555e-894b-d0e661ce628b,big chezza,28231a29-3548-5493-98df-5252a2bdf7c7,olli,25d2de46-e4f5-55a8-b6eb-d2662832b2db,CaaptainINT,095c58cc-75ef-5d07-a175-8f65760e438f,bbyracz,415d7a64-f6cc-5991-8324-aaeca8ae4219
1,2ddbb797-de1a-4fb9-a8df-998e3d9a6a5e,2025-06-30 17:59:00,blue,BurritoBandit,91c54dbe-0e4d-5918-bfc5-725f9012db9b,KamiranBilal,954c8f67-bf03-5003-aaac-98b6f441be1a,dvnielzzSigma,344892d3-84ca-5fbd-8eae-f247214b7d4d,ILoveSylvi,...,beb,06ec417a-53e2-5d0e-b85b-7d853da2b259,ulqizax,8f1219b0-8ed7-5265-af1a-4311d9592058,EKKIN,c225450e-5f74-52ff-a8f4-2aa382cb2abb,PetiBetter,09b7774e-2df1-5e2f-85c5-1fa00a13a293,KWN,a83ea350-30cd-5f1b-84b4-4fb79f37703a
2,4dfb220b-4871-443f-a8ba-b49c6304de5d,2025-07-01 20:07:00,blue,Michi,67f20954-a62f-50c8-911d-c98e8b1acf30,KlksmuzilA,ab6ce328-23fb-5ef7-b931-55cf56884367,bonjour,400ecf5d-1cef-5925-83fd-f88bc31b1044,olcia,...,r1n,ea8f3b79-ec89-5705-a6e0-31b19b04821b,FatOsiol14,f7ab3526-f4d5-56dd-8ec1-3381a072348e,namaldiv,e618dfef-34c1-5f2a-a587-c9165ec480e1,mezzz,9a6ffc2f-eff9-5473-91df-e04f0f9dcfa0,500YE,f25829c0-eb1b-5c84-9d05-0b4e1e4a9b90
3,5f0f52a5-a038-48b4-9c41-5509dd2daec5,2025-07-01 17:28:00,red,Imagine,1c852ccb-fbdf-5cdf-852d-9c49f3ba1208,Słabiak,76945efa-f8a4-5b28-866f-6d5803f57b46,Michi,67f20954-a62f-50c8-911d-c98e8b1acf30,Johnny Cage,...,Aistuks,79110e30-d5f5-5694-b684-d0694908cb09,boginii,d41acb9e-4e68-54eb-9ec3-e606ed0f20e0,Playboi kasti,f6fde59e-22c6-56bf-9383-d2907ee19dd8,PastoreCauto9731,5ad57a2a-9f66-55ab-b1e2-ec330920b1eb,saab rider,09d922c2-90d7-597c-ba63-5ff80f569dd1
4,34d4275e-a25c-4c07-a61d-07d01bb5ca53,2025-06-28 22:32:00,blue,sunset,af480097-db74-54ac-860e-d8f64567b789,lilizaardd31,78c50949-aa2f-5e0e-bd6f-8ec7cf8f180b,Michi,67f20954-a62f-50c8-911d-c98e8b1acf30,рин,...,Panterka,1196ca0a-8346-5034-b620-86056e567944,MisTerDiFrog,73d779fd-a64c-5a98-a756-bea88105e9b9,Nixyara,d109ae28-3383-5f6a-9db3-8ded3f881370,Snejinka,72d5e638-d241-52da-ae3f-8067f7c4da2b,PalkaIstiny,d5f73c20-4971-5350-93e2-681f54ae46d1

In [5]:
len(matchs_dataframe)

53

In [6]:
matchs_dataframe = matchs_dataframe[matchs_dataframe['start_datetime'] > MATCHS_EXPIRATION_LIMIT]

In [7]:
df = pd.read_csv(MATCHS_ENHANCED_FILE)
df.head()

,tier,score,kills,deaths,assists,headshots,bodyshots,legshots,damage_made,damage_received,level,puuid,match_id
0,0.000000,3467.000000,11.857143,12.142857,3.571429,3.428571,26.000000,5.000000,1602.285714,1586.571429,34,dccdeb22-4acb-5729-a2dc-276307a2b778,8c3781fa-d534-450c-a19d-faa38b173a79
1,1.444444,2955.388889,10.500000,14.111111,2.166667,5.611111,25.111111,2.444444,1765.388889,2309.888889,57,8da8a0b7-8c17-5f7c-8314-c3366d37ddb6,8c3781fa-d534-450c-a19d-faa38b173a79
2,2.555556,4446.944444,15.388889,11.777778,3.444444,10.555556,32.388889,2.222222,2866.777778,2210.888889,98,bfbe7379-4db6-5431-8ff2-85136eb73d2b,8c3781fa-d534-450c-a19d-faa38b173a79
3,8.792453,4396.226415,14.886792,15.867925,4.660377,7.698113,42.188679,4.547170,2915.754717,3025.924528,293,0ffc7adf-5652-5424-ae19-c06788070a88,8c3781fa-d534-450c-a19d-faa38b173a79
4,4.636364,4048.181818,13.818182,14.363636,4.090909,4.636364,46.727273,10.272727,2413.363636,2536.909091,94,d6cdb4e4-d26d-520d-b276-dc985bb58844,8c3781fa-d534-450c-a19d-faa38b173a79

In [8]:
len(df)

19

In [8]:
import sqlite3
from src.config import PLAYER_DB_PATH

# Connexion à la base (créée si elle n'existe pas)
conn = sqlite3.connect(PLAYER_DB_PATH)
cursor = conn.cursor()

# consultation de la base
cursor.execute('SELECT * FROM players')
rows = cursor.fetchall()
print(f"Nombre de lignes dans la table player: {len(rows)}")
for row in rows:
    print(row)

Nombre de lignes dans la table player: 407
('e8ef8695-423f-57c3-b5d7-7d013f79ec02', 'LEVIA10', 225, '5.77272727272727', 4436.772727272727, 14.636363636363637, 15.181818181818182, 5.545454545454546, 9.136363636363637, 43.54545454545455, 6.454545454545454, 2972.3636363636365, 2853.7727272727275, 22, '2025-07-14 22:08:11')
('91c54dbe-0e4d-5918-bfc5-725f9012db9b', 'BurritoBandit', 77, '4.90909090909091', 3565.3636363636365, 12.0, 16.363636363636363, 4.363636363636363, 4.909090909090909, 43.0, 8.0, 2254.818181818182, 3113.6363636363635, 11, '2025-07-14 22:08:12')
('67f20954-a62f-50c8-911d-c98e8b1acf30', 'Michi', 205, '5.95652173913043', 4825.478260869565, 16.52173913043478, 14.652173913043478, 6.260869565217392, 10.478260869565217, 49.30434782608695, 5.3478260869565215, 3156.391304347826, 3007.0, 23, '2025-07-14 22:08:13')
('1c852ccb-fbdf-5cdf-852d-9c49f3ba1208', 'Imagine', 70, '8.96', 4309.72, 14.68, 15.52, 5.52, 7.28, 33.6, 4.68, 3011.12, 3453.84, 25, '2025-07-14 22:08:16')
('af480097-db74-54ac-860e-d8f64567b789', 'sunset', 14, '0.833333333333333', 3382.0, 11.0, 16.0, 4.333333333333333, 9.0, 22.5, 2.1666666666666665, 2201.1666666666665, 2910.1666666666665, 6, '2025-07-14 22:08:16')
('d81b85e6-12c2-5026-8d7c-7b592d16f003', 'Sofia', 269, '6.92307692307692', 3486.1923076923076, 11.23076923076923, 15.73076923076923, 8.0, 5.576923076923077, 34.07692307692308, 5.461538461538462, 2345.4615384615386, 3021.4615384615386, 26, '2025-07-14 22:08:19')
('4f3a90b1-6df0-5fd8-b89e-9e9873b3aafc', 'ToXicNati', 148, '7.47058823529412', 4720.882352941177, 15.352941176470589, 15.882352941176471, 4.529411764705882, 8.470588235294118, 52.1764705882353, 3.5294117647058822, 3230.176470588235, 3010.8823529411766, 17, '2025-07-14 22:08:22')
('dccdeb22-4acb-5729-a2dc-276307a2b778', 'FratoMorto41', 35, '0.0', 3832.6, 13.2, 14.4, 4.6, 5.0, 40.2, 7.2, 2439.4, 2684.4, 5, '2025-07-14 22:08:22')
('3cae549f-2ba3-53d8-9216-55609ea8ee97', 'Anyadöntögető', 76, '9.14285714285714', 4512.238095238095, 16.38095238095238, 14.476190476190476, 2.9523809523809526, 13.428571428571429, 28.285714285714285, 1.5714285714285714, 2929.1428571428573, 3067.1428571428573, 21, '2025-07-14 22:08:25')
('cba69e40-636b-534c-810c-8ad0f474d385', 'vortex2deurm', 251, '8.9375', 4171.40625, 14.0, 17.46875, 5.34375, 10.0, 38.34375, 3.59375, 2741.375, 3361.4375, 32, '2025-07-14 22:08:27')
('6d5827ce-5b49-5445-9617-b63c36ee57f9', 'M8 lukyllstreak', 202, '8.82258064516129', 4772.564516129032, 16.20967741935484, 15.983870967741936, 5.064516129032258, 8.919354838709678, 46.41935483870968, 4.0, 3129.8225806451615, 3016.9032258064517, 62, '2025-07-14 22:08:29')
('d0ecb40c-5303-58dd-8a07-d02089a6f906', 'den glade gjøken', 168, '9.02857142857143', 4752.314285714286, 16.17142857142857, 15.228571428571428, 4.285714285714286, 6.914285714285715, 53.142857142857146, 9.742857142857142, 3029.0857142857144, 3090.1714285714284, 35, '2025-07-14 22:09:29')
('f922d0ec-ab29-58b0-824d-b20f33675016', 'ddos on peek', 11, '7.0', 5511.0, 19.583333333333332, 13.416666666666666, 3.4166666666666665, 15.416666666666666, 32.833333333333336, 1.3333333333333333, 3692.5, 2714.4166666666665, 12, '2025-07-14 22:09:32')
('1f8c22ff-87ee-5758-ba47-8f475651e6d8', 'JediInterference', 207, '9.86666666666667', 4738.433333333333, 16.366666666666667, 14.6, 6.066666666666666, 8.7, 45.96666666666667, 6.033333333333333, 3140.4666666666667, 2931.866666666667, 30, '2025-07-14 22:09:35')
('c5a960a1-694b-5b4d-a94d-d13e6daeb7a7', 'CookieBearr', 94, '11.1951219512195', 4768.073170731707, 17.097560975609756, 15.658536585365853, 3.5609756097560976, 14.878048780487806, 25.121951219512194, 1.7560975609756098, 3100.0731707317073, 3171.1951219512193, 41, '2025-07-14 22:09:36')
('3fb19d0b-a2c1-5099-abd1-b05c01de39f3', 'DD brlw', 143, '12.0238095238095', 4087.595238095238, 14.071428571428571, 13.952380952380953, 7.880952380952381, 9.142857142857142, 36.80952380952381, 2.7142857142857144, 2654.285714285714, 2741.404761904762, 42, '2025-07-14 22:09:37')
('deb34593-8b71-5f7d-825b-957d4c20fd79', 'Rashid Randwa', 141, '13.3333333333333', 4565.185185185185, 16.40740740740741, 14.592592592592593, 5.111111111111111, 10.74074074074074, 40.18518518518518, 3.259259259259259, 3057.740740740741, 2891.037037037037, 27, '2025-07-14 22:09:38')
('fe7b1d64-2039-5632-abfb-8ab4c28181ee', 'Qapil', 226, '13.64', 4515.106666666667, 15.72, 14.466666666666667, 5.066666666666666, 9.973333333333333, 44.013333333333335, 4.626666666666667, 2963.4133333333334, 2900.56, 75, '2025-07-14 22:09:39')
('992b6f90-c53e-59b7-b17d-c52cffecf0e6', 'Vlone', 79, '12.3333333333333', 4702.407407407408, 16.59259259259259, 14.703703703703704, 4.851851851851852, 12.481481481481481, 30.51851851851852, 2.6666666666666665, 3111.296296296296, 2914.6666666666665, 27, '2025-07-14 22:09:40')
('b1d13d91-c975-5e09-b5fd-82e33bb96fb0', 'Scary1', 140, '14.5714285714286', 4606.428571428572, 16.65714285714286, 14.6, 3.2857142857142856, 12.428571428571429, 28.37142857142857, 2.0, 3050.542857142857, 2810.4857142857145, 35, '2025-07-14 22:09:41')
('85611415-e76d-5fd2-88d0-61424089c32a', 'The chosen one', 106, '13.1363636363636', 4082.409090909091, 14.681818181818182, 14.272727272727273, 3.9545454545454546, 10.636363636363637, 28.545454545454547, 3.8181818181818183, 2688.0454545454545, 2685.409090909091, 22, '2025-07-14 22:09:42')
('ba737bd8-f207-551e-878e-caff613599d4', 'AJ4886', 60, '7.0', 4002.25, 13.916666666666666, 13.583333333333334, 3.8333333333333335, 8.666666666666666, 39.25, 3.9166666666666665, 2662.25, 2910.3333333333335, 12, '2025-07-14 22:09:43')
('46355aee-8867-5ed7-9a2f-4eb7260c90c8', 'Alphori', 43, '6.16666666666667', 3351.9166666666665, 10.916666666666666, 17.5, 4.083333333333333, 6.583333333333333, 53.0, 8.333333333333334, 2145.5, 3312.25, 12, '2025-07-14 22:09:44')
('e9437a1d-4f86-573f-82fc-08436aa3bd7e', 'Hippikayy93', 115, '9.08695652173913', 3025.5652173913045, 10.130434782608695, 14.91304347826087, 5.956521739130435, 5.217391304347826, 33.130434782608695, 4.043478260869565, 2026.304347826087, 2827.782608695652, 23, '2025-07-14 22:09:44')
('f27a33e3-40ed-5533-af21-3cd527288103', 'boxeur2mamie', 143, '10.0769230769231', 4953.0, 17.871794871794872, 14.76923076923077, 2.641025641025641, 14.820512820512821, 27.82051282051282, 2.2564102564102564, 3348.5128205128203, 2872.6923076923076, 39, '2025-07-14 22:10:46')
('9d0ae354-fd79-5290-9a5f-e838aa47ada1', 'Ketchup', 238, '9.37142857142857', 4898.685714285714, 17.114285714285714, 16.17142857142857, 5.2, 11.82857142857143, 36.25714285714286, 2.8285714285714287, 3236.6857142857143, 3200.4857142857145, 35, '2025-07-14 22:10:48')
('a7a83922-63df-5404-b1d5-f1721ed3c234', 'sev beni', 99, '10.4545454545455', 3691.2727272727275, 12.545454545454545, 17.181818181818183, 4.363636363636363, 10.636363636363637, 26.90909090909091, 1.9090909090909092, 2494.0, 3267.3636363636365, 11, '2025-07-14 22:10:49')
('47a982d0-aef2-5166-a8f8-5e5cd71570f6', 'swocker', 359, '14.35', 3321.7, 10.983333333333333, 14.333333333333334, 6.683333333333334, 7.4, 29.966666666666665, 3.466666666666667, 2284.3166666666666, 2761.233333333333, 60, '2025-07-14 22:10:51')
('0e795981-47d0-506b-8e5f-2d091efef2a6', 'L E O N', 229, '14.0277777777778', 4976.638888888889, 17.805555555555557, 15.777777777777779, 2.9722222222222223, 14.777777777777779, 24.444444444444443, 1.3888888888888888, 3226.1111111111113, 3148.5555555555557, 36, '2025-07-14 22:10:52')
('6077139b-d5bd-5474-9566-c060d8c70274', 'Captain Elia', 634, '16.2272727272727', 3862.121212121212, 13.575757575757576, 15.272727272727273, 3.9545454545454546, 10.484848484848484, 29.151515151515152, 2.106060606060606, 2539.5151515151515, 2979.4545454545455, 66, '2025-07-14 22:10:54')
('47ae06f8-e372-5829-a9e0-f4a4453f8792', 'Rego FiX', 120, '13.375', 6589.75, 22.708333333333332, 15.0, 6.416666666666667, 16.458333333333332, 46.791666666666664, 2.7916666666666665, 4381.583333333333, 3314.8333333333335, 24, '2025-07-14 22:10:55')
('e698ff94-7c6c-53b7-92a6-24f718e8d292', 'FlawlesKitty2', 130, '10.4615384615385', 4565.846153846154, 15.76923076923077, 16.384615384615383, 4.423076923076923, 11.384615384615385, 34.92307692307692, 2.9615384615384617, 2952.6923076923076, 3154.769230769231, 26, '2025-07-14 22:10:56')
('7ca463d1-1f2d-5204-bdcc-ab00e5afdf99', '3ashry73', 315, '10.3620689655172', 4176.017241379311, 14.293103448275861, 16.051724137931036, 4.827586206896552, 11.879310344827585, 23.689655172413794, 1.9655172413793103, 2858.5, 3161.655172413793, 58, '2025-07-14 22:10:57')
('4c93607b-066a-565d-a1a9-ccace416b956', 'Dumbledodge', 340, '13.1323529411765', 4069.029411764706, 13.926470588235293, 14.308823529411764, 4.8088235294117645, 9.102941176470589, 42.911764705882355, 3.1176470588235294, 2680.264705882353, 2680.8088235294117, 68, '2025-07-14 22:10:58')
('47a28b66-7eec-52a9-918b-1a523d38784d', 'eens', 82, '9.69230769230769', 6283.538461538462, 21.923076923076923, 15.692307692307692, 5.384615384615385, 17.153846153846153, 41.30769230769231, 2.769230769230769, 4040.230769230769, 3116.0, 13, '2025-07-14 22:11:01')
('efe68cfd-5a1f-597e-ab14-72556b52fdd5', 'Tkt jpeux lfaire', 155, '10.7727272727273', 3670.7272727272725, 12.363636363636363, 15.545454545454545, 4.7272727272727275, 8.772727272727273, 32.5, 1.7727272727272727, 2549.5, 2799.7272727272725, 22, '2025-07-14 22:11:04')
('def901f9-417d-54d8-a8df-dee6d6875981', 'Brenny', 275, '19.5421686746988', 4605.44578313253, 15.060240963855422, 15.987951807228916, 6.542168674698795, 9.373493975903614, 40.83132530120482, 3.5783132530120483, 3092.3132530120483, 3116.578313253012, 83, '2025-07-14 22:12:07')
('5499a222-11df-5cd9-ac53-5ea68a106d1f', 'XxyazhgarxX9', 60, '7.0', 4182.8, 14.5, 16.5, 5.5, 11.6, 33.5, 3.3, 2703.3, 3030.9, 10, '2025-07-14 22:12:07')
('82c9d243-e179-503c-996f-941018b9924d', 'pavlovic1998', 213, '11.84375', 4299.8125, 14.875, 15.09375, 4.90625, 9.8125, 36.71875, 3.65625, 2852.375, 3046.40625, 32, '2025-07-14 22:12:09')
('c98f2f14-08dc-5d8c-826d-30b0333de69a', 'CocoD3AL', 145, '9.84', 4159.64, 14.2, 15.92, 4.48, 10.64, 27.6, 2.24, 2771.28, 3043.68, 25, '2025-07-14 22:12:11')
('654351f6-c2aa-5af2-98f4-f219c449f855', 'LE M GRRRT BAW', 108, '8.65714285714286', 3886.4, 12.714285714285714, 15.628571428571428, 6.628571428571429, 8.914285714285715, 47.91428571428571, 5.685714285714286, 2520.4285714285716, 3035.2, 35, '2025-07-14 22:12:12')
('8e4d910a-9b86-581e-bab4-ef5960df4a13', 'Zwifreak', 59, '8.83333333333333', 4440.944444444444, 14.666666666666666, 14.666666666666666, 5.666666666666667, 7.0, 46.0, 4.0, 2978.3888888888887, 3008.0, 18, '2025-07-14 22:12:15')
('b4139920-10dd-5e25-a5be-800fb1a1c553', 'mejmiaou', 50, '3.33333333333333', 3542.8333333333335, 12.083333333333334, 14.333333333333334, 7.083333333333333, 8.5, 36.75, 3.0, 2297.9166666666665, 3003.0, 12, '2025-07-14 22:12:17')
('1d5713a0-f3a5-59a0-8361-79626941f4f8', 'bonsai1112', 97, '4.27586206896552', 3121.8275862068967, 10.241379310344827, 14.241379310344827, 5.689655172413793, 3.8275862068965516, 38.827586206896555, 10.172413793103448, 2046.8275862068965, 2930.2413793103447, 29, '2025-07-14 22:12:20')
('89b43153-1f17-518c-a68b-5c2c388c42a5', 'DI4BLOO', 104, '6.17647058823529', 3282.8823529411766, 11.529411764705882, 14.647058823529411, 4.764705882352941, 7.705882352941177, 28.88235294117647, 3.1176470588235294, 2104.0588235294117, 2846.235294117647, 17, '2025-07-14 22:12:21')
('2b3be82e-8f85-5c2a-a0a5-62e57a55c1b1', 'BATTEUR', 208, '3.95652173913043', 4105.04347826087, 14.565217391304348, 17.0, 4.695652173913044, 9.130434782608695, 34.869565217391305, 4.478260869565218, 2731.6521739130435, 3149.1739130434785, 23, '2025-07-14 22:12:22')
('1870fabe-d881-572d-82b6-2ad2586be521', 'uva azul', 137, '4.15789473684211', 3856.7368421052633, 12.578947368421053, 15.526315789473685, 4.842105263157895, 7.526315789473684, 39.1578947368421, 3.6842105263157894, 2534.5263157894738, 2950.4736842105262, 19, '2025-07-14 22:13:24')
('3fb08884-9056-52a1-8087-d8386538045c', 'Mcfly', 629, '18.4963503649635', 4304.291970802919, 14.386861313868613, 16.21167883211679, 6.562043795620438, 10.627737226277372, 47.416058394160586, 6.467153284671533, 2753.6131386861316, 3138.109489051095, 137, '2025-07-14 22:13:26')
('2319923a-0572-51a5-8218-955870af80a6', 'Kaito', 189, '19.3', 4245.95, 14.675, 15.6, 5.4625, 10.625, 33.4625, 2.6375, 2827.5875, 2989.875, 80, '2025-07-14 22:13:28')
('c7b89f83-3e4d-56c7-b4bd-949a8839e7ac', 'IM BAD', 514, '11.625730994152', 3972.7426900584796, 14.023391812865498, 11.783625730994151, 3.4327485380116958, 12.362573099415204, 26.391812865497077, 2.1169590643274856, 2559.654970760234, 2313.3801169590643, 171, '2025-07-14 22:13:31')
('53b85767-26dc-5c0c-9d9f-5fe3b69d81ae', 'Sabitzer', 421, '15.8', 4229.72, 14.42, 16.04, 4.82, 9.72, 34.8, 3.12, 2797.96, 3203.94, 50, '2025-07-14 22:13:34')
('a9f861d3-50c1-53f8-bd95-bf1fe3f9e850', 'thblk1', 173, '17.2702702702703', 3970.972972972973, 13.91891891891892, 15.594594594594595, 4.256756756756757, 10.64864864864865, 29.054054054054053, 2.635135135135135, 2700.189189189189, 3028.1486486486488, 74, '2025-07-14 22:13:35')
('ae6fdb13-7f1e-555e-894b-d0e661ce628b', 'Zandal', 184, '8.07619047619048', 3419.8952380952383, 11.228571428571428, 16.085714285714285, 5.285714285714286, 7.019047619047619, 39.304761904761904, 3.1333333333333333, 2345.504761904762, 3086.5809523809526, 105, '2025-07-14 22:13:36')
('06ec417a-53e2-5d0e-b85b-7d853da2b259', 'beb', 184, '7.4', 5593.4, 20.4, 15.2, 6.0, 13.6, 50.8, 2.6, 3666.2, 2879.4, 5, '2025-07-14 22:13:38')
('ea8f3b79-ec89-5705-a6e0-31b19b04821b', 'r1n', 96, '8.69230769230769', 5235.153846153846, 18.076923076923077, 17.307692307692307, 3.3846153846153846, 13.923076923076923, 25.384615384615383, 1.9230769230769231, 3367.846153846154, 3117.769230769231, 13, '2025-07-14 22:13:41')
('79110e30-d5f5-5694-b684-d0694908cb09', 'Aistuks', 26, '6.90909090909091', 4004.090909090909, 13.272727272727273, 16.09090909090909, 3.909090909090909, 9.0, 35.27272727272727, 3.1818181818181817, 2696.7272727272725, 3001.6363636363635, 11, '2025-07-14 22:14:42')
('1196ca0a-8346-5034-b620-86056e567944', 'Panterka', 112, '7.84', 4528.36, 15.56, 16.76, 5.16, 9.2, 51.0, 4.0, 2954.4, 3328.12, 25, '2025-07-14 22:14:43')
('7a7c0517-f0ac-5a89-a385-d2cc02394764', 'learsusss夢', 128, '6.52941176470588', 3269.705882352941, 10.823529411764707, 13.294117647058824, 5.0, 8.882352941176471, 29.764705882352942, 2.8823529411764706, 2201.470588235294, 2577.4117647058824, 17, '2025-07-14 22:14:46')
('dc1267e8-5872-5e5c-8a1b-8acabcd8f6e1', 'FanofPanda', 86, '7.52631578947368', 4438.789473684211, 15.947368421052632, 15.68421052631579, 4.421052631578948, 11.68421052631579, 37.78947368421053, 4.157894736842105, 2950.6315789473683, 3153.5263157894738, 19, '2025-07-14 22:14:48')
('5eb37e38-1198-5a78-ad22-38457dee78b9', 'Meguru', 180, '5.04761904761905', 2239.0, 7.238095238095238, 15.80952380952381, 5.428571428571429, 6.190476190476191, 17.38095238095238, 1.0952380952380953, 1556.1904761904761, 3005.190476190476, 21, '2025-07-14 22:14:49')
('07bdc21d-c22e-5076-89ac-66eba8de7e2a', 'digsand', 173, '5.09090909090909', 2616.909090909091, 9.409090909090908, 12.5, 4.7727272727272725, 4.318181818181818, 38.36363636363637, 7.5, 1718.9545454545455, 2425.090909090909, 22, '2025-07-14 22:14:51')
('3b6acccf-ca6c-5d24-8e39-1352fd57cc88', 'nssiyuu', 129, '7.97058823529412', 3981.1176470588234, 13.911764705882353, 15.323529411764707, 5.205882352941177, 7.676470588235294, 42.64705882352941, 4.382352941176471, 2673.9411764705883, 3154.0, 34, '2025-07-14 22:14:52')
('96bb7590-4e9c-5b2b-a56e-25cc6570246e', 'loopi', 30, '4.54545454545455', 2109.181818181818, 7.0, 15.636363636363637, 5.363636363636363, 3.5454545454545454, 25.636363636363637, 7.0, 1461.3636363636363, 3539.4545454545455, 11, '2025-07-14 22:14:55')
('c65cea05-a7df-5193-ad26-81406f0f9ad7', 'ygk ッ', 94, '9.19047619047619', 4533.571428571428, 15.619047619047619, 15.0, 3.7142857142857144, 12.095238095238095, 33.857142857142854, 1.5238095238095237, 3021.7619047619046, 2881.9523809523807, 21, '2025-07-14 22:14:56')
('39ca4bbc-f147-5d9d-932a-e856a30b30c8', 'lordyamen466', 160, '11.1428571428571', 5405.619047619048, 19.61904761904762, 15.0, 3.761904761904762, 11.714285714285714, 36.476190476190474, 3.857142857142857, 3530.4761904761904, 3037.0476190476193, 21, '2025-07-14 22:14:58')
('cf1dd67e-cedb-569b-b43f-25d5920aa6c9', 'YSS69', 67, '8.8', 4076.3, 13.65, 15.6, 5.35, 6.9, 44.55, 4.3, 2784.65, 2958.75, 20, '2025-07-14 22:16:01')
('5cd596cd-5363-550c-89f0-9e5067b2f706', 'Veloria', 44, '8.94117647058824', 4247.411764705882, 15.058823529411764, 13.823529411764707, 2.823529411764706, 11.470588235294118, 30.941176470588236, 2.3529411764705883, 2792.235294117647, 2714.3529411764707, 17, '2025-07-14 22:16:04')
('768cf0c0-0a76-5bcd-9a93-a882e2d06711', 'munse', 453, '8.89090909090909', 3256.2363636363634, 11.2, 14.472727272727273, 5.490909090909091, 9.418181818181818, 31.236363636363638, 2.018181818181818, 2189.072727272727, 2837.2363636363634, 55, '2025-07-14 22:16:05')
('3c09a001-beee-5586-a56d-99c2fe4de03f', 'Azazel', 99, '14.2244897959184', 4240.673469387755, 14.673469387755102, 14.612244897959183, 4.408163265306122, 11.428571428571429, 29.224489795918366, 3.204081632653061, 2773.0, 2757.591836734694, 49, '2025-07-14 22:16:06')
('64abd33d-a273-5835-9808-a52639f5172f', 'cocomoYT', 224, '16.85', 4155.25, 14.525, 14.325, 4.675, 11.425, 35.9, 2.55, 2795.425, 2684.075, 40, '2025-07-14 22:16:09')
('79d7cea0-4c4b-578d-8ab6-99ae57184398', 'ツCrimsツ', 102, '15.4583333333333', 5655.208333333333, 19.125, 16.125, 6.041666666666667, 14.041666666666666, 45.291666666666664, 3.4583333333333335, 3826.0416666666665, 3291.0833333333335, 24, '2025-07-14 22:16:11')
('994530d9-63c2-5325-955d-24303d11eafb', 'Y O U', 118, '16.25', 4566.21875, 15.46875, 16.375, 5.0625, 11.25, 46.9375, 4.625, 3033.46875, 3254.46875, 32, '2025-07-14 22:16:12')
('cf9a583b-99dd-5248-a470-8bc31fe56afe', 'len1406', 116, '7.96666666666667', 4786.766666666666, 16.266666666666666, 18.2, 5.166666666666667, 11.633333333333333, 35.03333333333333, 3.2666666666666666, 3165.3333333333335, 3434.0, 30, '2025-07-14 22:16:13')
('c9b5d1b5-57d6-534a-a214-290798ea49a2', 'zorro', 37, '6.94736842105263', 2984.5789473684213, 9.894736842105264, 13.157894736842104, 4.0, 4.2105263157894735, 35.21052631578947, 10.789473684210526, 1976.2631578947369, 2642.0526315789475, 19, '2025-07-14 22:16:14')
('e51fafb1-f606-5240-8acf-657249199a99', 'Femto', 106, '9.53333333333333', 4230.111111111111, 15.2, 16.31111111111111, 4.511111111111111, 12.733333333333333, 24.755555555555556, 2.088888888888889, 2850.6222222222223, 3063.1111111111113, 45, '2025-07-14 22:16:15')
('8c1511d2-1ac8-543b-8ef3-974b51e1641c', 'TopFraggXD', 134, '7.55', 4187.85, 14.375, 16.475, 3.85, 11.4, 31.95, 2.7, 2816.9, 3301.875, 40, '2025-07-14 22:16:16')
('c1170261-55db-5579-859a-0169e783eccd', 'ｉｃｅｌｏｖｅ', 97, '7.71428571428571', 5272.821428571428, 17.607142857142858, 16.107142857142858, 6.928571428571429, 9.892857142857142, 49.92857142857143, 7.071428571428571, 3488.75, 3181.6428571428573, 28, '2025-07-14 22:17:19')
('62cd389d-8404-521d-a5b2-06c8978e0b3a', 'Zone', 88, '13.7', 7033.3, 24.4, 16.4, 4.5, 16.8, 50.9, 4.8, 4530.9, 3362.0, 10, '2025-07-14 22:17:22')
('34e1c3eb-6366-5d96-b256-401e67877734', '天才的', 91, '11.25', 5176.9, 17.35, 17.05, 3.95, 12.75, 41.15, 3.45, 3390.65, 3345.6, 20, '2025-07-14 22:17:22')
('cc702976-f443-520a-998d-36a781d4f7d7', 'babaprox3127', 65, '11.7727272727273', 4501.363636363636, 15.318181818181818, 18.0, 5.045454545454546, 10.363636363636363, 39.31818181818182, 4.136363636363637, 2947.1363636363635, 3474.181818181818, 22, '2025-07-14 22:17:23')
('eab25cfd-f2b5-59d1-bbc1-ea729d237648', 'sürmenebıçağı', 67, '15.2380952380952', 4663.0, 16.0, 16.238095238095237, 4.190476190476191, 13.047619047619047, 29.714285714285715, 2.142857142857143, 3092.5238095238096, 3139.2380952380954, 21, '2025-07-14 22:17:26')

In [12]:
import pandas as pd
import sqlite3
from src.config import PLAYER_DB_PATH

# Lire juste les colonnes (sans données)
with sqlite3.connect(PLAYER_DB_PATH) as conn:
    df = pd.read_sql_query("SELECT * FROM players LIMIT 0", conn)
    print("Colonnes:", df.columns.tolist())

Colonnes: ['puuid', 'name', 'level', 'tier', 'score', 'kills', 'deaths', 'assists', 'headshots', 'bodyshots', 'legshots', 'damage_made', 'damage_received', 'match_count', 'updated_at']

In [ ]:
import sqlite3
from src.config import PLAYER_DB_PATH

# Connexion à la base (créée si elle n'existe pas)
conn = sqlite3.connect(PLAYER_DB_PATH)
cursor = conn.cursor()

# consultation de la base
cursor.execute('SELECT * FROM players')
rows = cursor.fetchall()
print(f"Nombre de lignes dans la table player: {len(rows)}")
for row in rows:
    print(row)

# Preprocess

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
from src.config import PLAYER_DB_PATH, MATCHS_FILE
import sqlite3

# For each match, we will predict the winner
# Load the matches data
matchs_df = pd.read_csv(MATCHS_FILE, parse_dates=['start_datetime'])
# Load the players data
with sqlite3.connect(PLAYER_DB_PATH) as conn:
    players_df = pd.read_sql_query("SELECT * FROM players", conn)